name: redis
release:
    repo: "https://github.com/hkumarmk/redis-boshrelease.git"
    branch: master
# deployment manifest repo. Default to release_repo
manifest:
  repo: "https://github.com/hkumarmk/redis-boshrelease.git"
  # Path to deployment manifest within manifest repo default to manifest.yml
  path: manifests/redis.yml
stemcells:
  - bosh-warden-boshlite-ubuntu-trusty-go_agent
